### ISSUE TITLE
BFF installation error

### ISSUE THREAD

**Issue by lobosan** [RedElastic/reactive-stock-trader#86]
Hi, I'm following the instructions to deploy to minikube and I'm having this error after adding the secret and deleting the pod doesn't help.

The logs of the pod look as follows:
`Cannot load module[Module [FormattersModule] cannot be instantiated.]
	at play.api.inject.Modules$.constructModule(Module.scala:181)
	at play.api.inject.Modules$.$anonfun$locate$4(Module.scala:140)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at play.api.inject.Modules$.locate(Module.scala:135)
	at play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:303)
	at play.api.inject.guice.GuiceApplicationBuilder$.$anonfun$$lessinit$greater$default$9$1(GuiceApplicationBuilder.scala:36)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:115)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:156)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: FormattersModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.api.inject.Modules$.$anonfun$locate$5(Module.scala:140)
	at play.api.inject.Modules$.constructModule(Module.scala:152)
	... 21 more`

**Comment by rocketpages** [comment]
Resolved this issue while preparing for an upgrade to Lagom 1.6.x
